application:
  title: MANNA
  version: v0.0.1

server:
  port: 9000
  shutdown: graceful

spring:
#  sql:
#    init:
#      mode: always
#      mode: never
  application:
    name: manna-api-service

  jackson:
    default-property-inclusion: non_null

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/manna
    username: manna
    password: manna!@34

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

logging:
  file.path: ${file-path.root}/logs
  file.name: ${spring.application.name}-${spring.config.activate.on-profile}
  config: classpath:logback-${spring.config.activate.on-profile}.xml

---
# LOCAL
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/Study/h2/manna/test;mode=mysql
      username: sa
      password:

  h2:
    console:
      enabled: true

file-path:
  root: /Users/ds/Downloads/springboot/${application.title}/${spring.application.name}

---
# DEV
spring:
  config:
    activate:
      on-profile: dev

file-path:
  root: /Users/ds/Downloads/springboot/${application.title}/${spring.application.name}

---
# TEST
spring:
  config:
    activate:
      on-profile: test

file-path:
  root: /Users/ds/Downloads/springboot/${application.title}/${spring.application.name}

---
# PROD
spring:
  config:
    activate:
      on-profile: prod

file-path:
  root: /Users/ds/Downloads/springboot/${application.title}/${spring.application.name}